[package]
name = "games"
version = "0.1.0"
edition = "2021"
authors = ["Felix Jablinski"]

[dependencies]
rand = "0.8.5"
mentor = { path = "../" }

[[bin]]
name = "connect4"
path = "src/bin/connect4.rs"

[[bin]]
name = "client"
path = "src/bin/chess.rs"
