[package]
name = "mentor"
version = "0.1.0"
edition = "2021"
authors = ["Felix Jablinski"]

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"

[workspace]
members = ["games", "network"]
resolver = "2"